arskom/spyne

- spyne/const/xml_ns.py
According to http://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383492
SOAP 1.1 namespaces are:
- http://schemas.xmlsoap.org/soap/envelope/
- http://schemas.xmlsoap.org/soap/encoding/
(with final slash)
But according to http://www.w3.org/TR/soap12-part1/#soapenvelope
SOAP 1.2 namespaces are:
- http://www.w3.org/2003/05/soap-envelope
- http://www.w3.org/2003/05/soap-encoding
(no final slash)
> soap12: fix namespaces (no final slash)

- spyne/test/interop/test_django.py
- spyne/util/django.py
This PR makes email pattern more strict. Now emails from top level domains (TLDs) are considered invalid. I.e. `about@me` is invalid email.
Updated regex: `about@example.com-` is also invalid
> exclude TLDs from valid emails

- doc/source/manual/03_types.rst
The code block at http://spyne.io/docs/2.10/manual/03_types.html#primitives has no colors because of invalid syntax (extra `@`).  I fixed that and a few other typos in the text.
> Fix some typos and reindent blocks

- spyne/protocol/_inbase.py
- spyne/test/interop/test_django.py
The `if string is None` test should be first, since `from_string` and `from_unicode` may be called with string=None in some cases (e.g. request in the unit test)
> Fixes from_unicode and from_string

- spyne/protocol/soap/soap12.py
If the faultcodes list is empty, child_subcode remains 0 (== Internal Server Error), which is okay. But it is not wrapped in an element.
This PR fixes it.
> Soap12 support: fixes error envelop for empty faultcodes list

- spyne/interface/xml_schema/model.py
Ensure the xmlAttribute element is generated in the correct location in the schema. In the case that the Model is *extended* then the attribute must be placed inside the `<xs:extension>` tag, rather than the `<xs:complexType>` tag.
In this case, appending it to sequence_parent is perfect because on an extended model the sequence_parent is the extension tag, and on a normal model the sequence_parent is the complexType tag.
Fixes https://github.com/arskom/spyne/issues/491
> Generate XmlAttribute in the correct location.

- spyne/model/complex.py
- spyne/test/model/test_complex.py
When you have ComplexModels which subclass other models then `get_serialization_instance` is not settings values of fields from base model. 
Check my unit test for details (this tests fails on current version).
> Proper serialization of inherited ComplexModels

- spyne/decorator.py
- spyne/model/primitive/__init__.py
1.  pop from kparams broke ability to use given instance for several calls - this is especially usefull in unit tests - as severall tests could be run on single instance - making a copy of kparams before popping fixes it
2. PositiveInteger was missing from __init__.py
> 2 simple fixes: allow multiple calls from single instance and add PositiveInteger to __init__.py

- spyne/util/__init__.py
Exceptions should not be silenced automatically - so I backported fix from 2.13 - please merge it.
> Backport of fix of silenced exceptions from 2.13

- spyne/model/primitive/datetime.py
- spyne/test/model/test_primitive.py
In previous version we could not use min or max for Date and Time fields as inclusive border because they were catch by exclusive.
From attached unittests `test_time_extreme_boundary` and `test_date_extreme_boundary` was failing, while test_datetime_extreme_boundary was passing.
> Fixed inclusive boundaries for Date and Time fields

- examples/django/rpctest/settings.py
- setup.py
- tox.ini
Django 1.11 is new LTS version and django 1.9 ended is support on April 2017 so it should be discourage to use as it has lack of security patches.
> feat(django): added support for django 1.11 and remove support 1.9

- spyne/decorator.py
With the example of `_out_message_name = "{http://example.org/}MyResponse"`
old behaviour:
`ns = "{http://example.org/}"` but still `_out_message_name = "{http://example.org/}MyResponse"`
fixed behaviour:
`ns = "{http://example.org/}"` and now `_out_message_name = "MyResponse"`
This fixes a bug I am experiencing in my application.
> Fix for using a ns prefixed `_out_message_name` when using 'bare' bodystyle.

- spyne/protocol/soap/soap12.py
Patch to suppress warning I am getting:
/usr/local/lib/python2.7/site-packages/spyne/protocol/soap/soap12.py:76: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
while subcode:
/usr/local/lib/python2.7/site-packages/spyne/protocol/soap/soap12.py:142: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
if role:
> Lxml warnings

- spyne/model/complex.py
- spyne/util/odict.py
Just delete the key from the dictionary first and then try to delete it
from the list.
> Fix wrong exception thrown from __delitem__ when key is missing.

- spyne/decorator.py
- spyne/interface/wsdl/wsdl11.py
- spyne/test/interface/wsdl/port_service_services.py
The documentation in decorator.py states, that _port_type
should be used to set the port type - nevertheless instead of
_port_type _soap_port_type is picked up.
The patch adapts the source code to the documentation and uses
_port_type.
> Renamed _soap_port_type to _port_type

- spyne/model/complex.py
Fixes #578 
`get_flat_type_info` expects a class argument instead of an instance. Passing a model instance as an argument can cause a memory leak as outlined in the issue.
> Fix memory leak in ComplexModelBase.as_dict

- spyne/context.py
- spyne/test/test_null_server.py
Otherwise, setting:
`spyne.const.MIN_GC_INTERVAL = float('inf')`
after `spyne.context` was imported would be useless.
You would need to also set:
`spyne.context.MIN_GC_INTERVAL = float('inf')`
like we needed to set:
`pyne._base.MIN_GC_INTERVAL = float('inf')` before c1dd218ea.
> Tweak MIN_GC_INTERVAL import

- spyne/interface/xml_schema/parser.py
Fixes XML parser issues on schemas with no type attribute defined
> Add NoneType check to get_type method

- spyne/decorator.py
- spyne/interface/wsdl/wsdl11.py
- spyne/model/_base.py
Addresses [#543](https://github.com/arskom/spyne/issues/543)
I've also had the need from a vendor spec to require the part name changed to "parameters".
Here's a solution without the need to hardcode wsdl11.py
> Allow wsdl message part:name change

- spyne/model/complex.py
logger.debug(traceback.print_stack()) means that stack is first printed and then None is passed to logger.debug, resulting in tons of unnecessary output that cannot be suppressed.
> Changing print_stack to format_stack

- spyne/server/wsgi.py
1. Using serverless-wsgi, URL params are encode as ?wsdl=, which spyne doesn't detect as a WSDL request. Remove "=" for this case.
2. The URL returned in the location includes ?wsdl. Add code to strip "?wsdl" and ".wsdl" from this response.
> Fix wsdl request

- doc/source/manual/03_types.rst
It seems there is a typo in Models/Types documentation. Customization examples refer to field `max_length`, though actual name of this field is `max_len`: https://github.com/arskom/spyne/blob/master/spyne/model/primitive/string.py#L53
> Fix name of an Attribute field in Types doc

- spyne/server/twisted/msgpack.py
This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.
> Use chain.from_iterable in msgpack.py

- spyne/util/etreeconv.py
Since Python 3.3, using or importing the ABCs from 'collections'  instead of using 'collections.abc' is deprecated. 
In Python 3.10, it is no longer supported.
Fixes: #676
> Fix usage of Python collections

- setup.py
According to the file headers, the license of *spyne* is LPGL-2.1-or-later. This PR makes this clear from the package license itself as well.
> DOC: Make license more clear
